Revisão de traduções (Trabalhos, departamentos, roupas e placas)
Scomossor/Gaby-Station pull request #68
Opened 2024-12-23 21:57 UTC by joshepvodka

## About the PR
Mudanças:
- O departamento cargo agora é chamado de "Departamento de Logística"
- padroniza todas as menções do chefe da segurança para "segurança chefe"
- padroniza todas as menções do chefe da engenharia para "engenheiro chefe"
- Intendente de carga é "intendente logístico"
- padroniza todas as menções de quartermaster para "intendente logístico"
- especialistas de salvatagem são "especialista de exploração"
- brigmedic é "clínico brigadista" (pode ser também médico brigadista/da brigada ou médico de combate)
- blueshield é "sentinela de comando"
- todas as menções da CentComm foram padronizadas para estar escrito exatamaente "CentComm" (em vez de Centcomm, CentCom, centcom, centcomm).
- agentes da CBURN foram renomeados para "agente de contenção biológica"
- a sigla CBURN foi renomeada para "DQBRN" (Defesa Quimica, Biológica, Radiológica e Nuclear. um batalhão do exército brasileiro que realmente existe que nem a CBRN da união européia e dos estados unidos)
- membros da deathsquad foram renomeado para "agente de exterminação"
- "deathsquad" agora é esquadrão da morte (um esquadrão de verdade que existiu durante a ditadura militar)
- hardsuits agora são "armaduras" (faz mais sentido do que tu pensa)
- trajes eva agora são "trajes aev" (Atividade ExtraVeicular)
- trajes de bioproteção agora são "trajes para perigo biológico" (o nome usado na industria)
- trajes anti-radiação agora são "trajes de proteção nuclear" (também o nome usado na industria)
- colete alta-viz agora é "colete refletivo" (o nome correto)
- agasalhos agora são chamados de casacos
- sindicato sendo um nome próprio tem letra maiúscula
- traduz todas as placas.

## Why / Balance

Aqui é brasil, ingles é pra gringo.

## Technical details

## Media

## Requirements

- [ ] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [ ] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes

**Changelog**

2024-12-23 23:47 UTC, AgentePanela requested changes
A sigla da centcom é centcom e nao centcomm
`"Slang for Central Command is 'CentCom"`
[Central Command](https://wiki.spacestation14.com/wiki/Central_Command)

2024-12-23 23:47 UTC, AgentePanela commented on Resources/Locale/pt-BR/Entities/Clothing/Back/duffel.ftl
> +ent-ClothingBackpackDuffelCBURN = mala da DQBRN
```suggestion
ent-ClothingBackpackDuffelCBURN = mala de CBURN
```

2024-12-23 23:47 UTC, AgentePanela commented on Resources/Locale/pt-BR/Entities/Clothing/Ears/headsets.ftl
> +ent-ClothingHeadsetCentCom = fone de ouvido da CentComm
```suggestion
ent-ClothingHeadsetCentCom = fone de ouvido da Central de Comando
```

2024-12-23 23:47 UTC, AgentePanela commented on Resources/Locale/pt-BR/Entities/Clothing/Ears/headsets.ftl
>  ent-ClothingHeadsetScience = fone de ouvido de pesquisas
```suggestion
ent-ClothingHeadsetScience = fone de ouvido de pesquisa
```

2024-12-23 23:47 UTC, AgentePanela commented on Resources/Locale/pt-BR/Entities/Clothing/Ears/headsets.ftl
>  ent-ClothingHeadsetCommand = fone de ouvido de comando
```suggestion
ent-ClothingHeadsetCommand = fone de ouvido do comando
```

2024-12-23 23:47 UTC, AgentePanela commented on Resources/Locale/pt-BR/Entities/Clothing/Ears/headsets_alt.ftl
> +ent-ClothingHeadsetAltCentCom = headset da CentComm
```suggestion
ent-ClothingHeadsetAltCentCom = headset da Central de Comando
```

2024-12-23 23:47 UTC, AgentePanela commented on Resources/Locale/pt-BR/Entities/Clothing/Ears/headsets_alt.ftl
> +ent-ClothingHeadsetAltCargo = headset do intendente logístico
```suggestion
ent-ClothingHeadsetAltCargo = headset do intendente de logística
```

2024-12-23 23:47 UTC, AgentePanela commented on Resources/Locale/pt-BR/Entities/Clothing/Ears/headsets_alt.ftl
> +ent-ClothingHeadsetAltCentComFake = headset da CentComm
```suggestion
ent-ClothingHeadsetAltCentComFake = headset da Central de Comando
```

2024-12-23 23:47 UTC, AgentePanela commented on Resources/Locale/pt-BR/Entities/Clothing/Head/hardsuit-helmets.ftl
> +ent-ClothingHeadHelmetCBURN = capacete da DQBRN
```suggestion
ent-ClothingHeadHelmetCBURN = capacete de CBURN
```

2024-12-23 23:47 UTC, AgentePanela commented on Resources/Locale/pt-BR/Entities/Clothing/Head/hats.ftl
> +ent-ClothingHeadHatCentcom = chapéu da CentComm
```suggestion
ent-ClothingHeadHatCentcom = chapéu da Central de Comando
```

2024-12-23 23:47 UTC, AgentePanela commented on Resources/Locale/pt-BR/Entities/Clothing/OuterClothing/hardsuits.ftl
> +ent-ClothingOuterHardsuitEVA = traje aev
```suggestion
ent-ClothingOuterHardsuitEVA = traje EVA
```

2024-12-23 23:47 UTC, AgentePanela commented on Resources/Locale/pt-BR/Entities/Clothing/OuterClothing/hardsuits.ftl
> +ent-ClothingOuterHardsuitEVAPrisoner = traje aev de prisioneiro
```suggestion
ent-ClothingOuterHardsuitEVAPrisoner = traje EVA de prisioneiro
```

2024-12-23 23:47 UTC, AgentePanela commented on Resources/Locale/pt-BR/Entities/Clothing/OuterClothing/hardsuits.ftl
> +ent-ClothingOuterHardsuitSyndicate = traje aev do Sindicato
```suggestion
ent-ClothingOuterHardsuitSyndicate = traje EVA do Sindicato
```

2024-12-23 23:47 UTC, AgentePanela commented on Resources/Locale/pt-BR/Entities/Clothing/OuterClothing/hardsuits.ftl
> +ent-ClothingOuterHardsuitMedical = armadura biológica do médico chefe
```suggestion
ent-ClothingOuterHardsuitMedical = hardsuit biológica do médico chefe
```

2024-12-23 23:47 UTC, AgentePanela commented on Resources/Locale/pt-BR/Entities/Clothing/OuterClothing/hardsuits.ftl
> +ent-ClothingOuterHardsuitRd = armadura experimental de pesquisador
```suggestion
ent-ClothingOuterHardsuitRd = hardsuit experimental de pesquisador
```

2024-12-23 23:47 UTC, AgentePanela commented on Resources/Locale/pt-BR/Entities/Clothing/OuterClothing/hardsuits.ftl
> +ent-ClothingOuterHardsuitSalvage = armadura de exploração
```suggestion
ent-ClothingOuterHardsuitSalvage = hardsuit de exploração
```

2024-12-23 23:47 UTC, AgentePanela commented on Resources/Locale/pt-BR/Entities/Clothing/OuterClothing/hardsuits.ftl
> +ent-ClothingOuterHardsuitSecurity = armadura de segurança
```suggestion
ent-ClothingOuterHardsuitSecurity = hardsuit de segurança
```

2024-12-23 23:47 UTC, AgentePanela commented on Resources/Locale/pt-BR/Entities/Clothing/OuterClothing/hardsuits.ftl
> +ent-ClothingOuterHardsuitSecurityRed = armadura do segurança chefe
```suggestion
ent-ClothingOuterHardsuitSecurityRed = hardsuit do segurança chefe
```

2024-12-23 23:47 UTC, AgentePanela commented on Resources/Locale/pt-BR/Entities/Clothing/OuterClothing/hardsuits.ftl
> +ent-ClothingOuterHardsuitSyndie = armadura do Sindicato
```suggestion
ent-ClothingOuterHardsuitSyndie = hardsuit do Sindicato
```

2024-12-23 23:47 UTC, AgentePanela commented on Resources/Locale/pt-BR/Entities/Clothing/OuterClothing/hardsuits.ftl
> +ent-ClothingOuterHardsuitWizard = armadura de arcana
```suggestion
ent-ClothingOuterHardsuitWizard = hardsuit de arcana
```

2024-12-23 23:47 UTC, AgentePanela commented on Resources/Locale/pt-BR/Entities/Clothing/OuterClothing/hardsuits.ftl
> +ent-ClothingOuterHardsuitLing = armadura bio-orgânica espacial
```suggestion
ent-ClothingOuterHardsuitLing = hardsuit bio-orgânica espacial
```

2024-12-23 23:47 UTC, AgentePanela commented on Resources/Locale/pt-BR/Entities/Clothing/OuterClothing/hardsuits.ftl
> +ent-ClothingOuterHardsuitSpatio = armadura de espaçonauta
```suggestion
ent-ClothingOuterHardsuitSpatio = hardsuit de espaçonauta
```

2024-12-23 23:47 UTC, AgentePanela commented on Resources/Locale/pt-BR/Entities/Clothing/OuterClothing/hardsuits.ftl
> +ent-ClothingOuterHardsuitJuggernaut = armadura Ultra-Blindada Cybersun
```suggestion
ent-ClothingOuterHardsuitJuggernaut = hardsuit Ultra-Blindada Cybersun
```

2024-12-23 23:47 UTC, AgentePanela commented on Resources/Locale/pt-BR/Entities/Clothing/OuterClothing/hardsuits.ftl
> +ent-ClothingOuterHardsuitSyndieCommander = armadura de comandante do Sindicato
```suggestion
ent-ClothingOuterHardsuitSyndieCommander = hardsuit de comandante do Sindicato
```

2024-12-23 23:47 UTC, AgentePanela commented on Resources/Locale/pt-BR/Entities/Clothing/OuterClothing/hardsuits.ftl
> +ent-ClothingOuterHardsuitSyndieElite = armadura de elite do Sindicato
```suggestion
ent-ClothingOuterHardsuitSyndieElite = hardsuit de elite do Sindicato
```

2024-12-23 23:47 UTC, AgentePanela commented on Resources/Locale/pt-BR/Entities/Clothing/OuterClothing/hardsuits.ftl
> +ent-ClothingOuterHardsuitCBURN = trage protetivo da DQBRN
```suggestion
ent-ClothingOuterHardsuitCBURN = hardsuit protetiva de CBURN
```

2024-12-23 23:47 UTC, AgentePanela commented on Resources/Locale/pt-BR/Entities/Clothing/OuterClothing/hardsuits.ftl
> +ent-ClothingOuterHardsuitERTLeader = armadura de líder da ERT
```suggestion
ent-ClothingOuterHardsuitERTLeader = hardsuit de líder da ERT
```

2024-12-23 23:47 UTC, AgentePanela commented on Resources/Locale/pt-BR/Entities/Clothing/OuterClothing/hardsuits.ftl
> +ent-ClothingOuterHardsuitERTEngineer = armadura de engenheiro da ERT
```suggestion
ent-ClothingOuterHardsuitERTEngineer = hardsuit de engenheiro da ERT
```

2024-12-23 23:47 UTC, AgentePanela commented on Resources/Locale/pt-BR/Entities/Clothing/OuterClothing/hardsuits.ftl
> +ent-ClothingOuterHardsuitERTMedical = armadura de paramédico da ERT
```suggestion
ent-ClothingOuterHardsuitERTMedical = hardsuit de medico da ERT
```

2024-12-23 23:47 UTC, AgentePanela commented on Resources/Locale/pt-BR/Entities/Clothing/OuterClothing/hardsuits.ftl
> +ent-ClothingOuterHardsuitERTSecurity = armadura de segurança da ERT
```suggestion
ent-ClothingOuterHardsuitERTSecurity = hardsuit de segurança da ERT
```

2024-12-23 23:47 UTC, AgentePanela commented on Resources/Locale/pt-BR/Entities/Clothing/OuterClothing/hardsuits.ftl
> +ent-ClothingOuterHardsuitERTJanitor = armadura de zelador da ERT
```suggestion
ent-ClothingOuterHardsuitERTJanitor = hardsuit de zelador da ERT
```

2024-12-23 23:47 UTC, AgentePanela commented on Resources/Locale/pt-BR/Entities/Clothing/Uniforms/jumpsuits.ftl
> +ent-ClothingUniformJumpsuitCentcomOfficial = macacão oficial do CentComm
```suggestion
ent-ClothingUniformJumpsuitCentcomOfficial = macacão oficial da Central de Comando
```

2024-12-23 23:47 UTC, AgentePanela commented on Resources/Locale/pt-BR/Entities/Clothing/Uniforms/jumpsuits.ftl
> +    .desc = É um macacão usado pelos dirigentes do CentComm.
```suggestion
    .desc = É um macacão usado pelos dirigentes da Central de Comando
```

2024-12-23 23:47 UTC, AgentePanela commented on Resources/Locale/pt-BR/Entities/Clothing/Uniforms/jumpsuits.ftl
> +ent-ClothingUniformJumpsuitCentcomOfficer = macacão de oficial do CentComm
```suggestion
ent-ClothingUniformJumpsuitCentcomOfficer = macacão de oficial da Central de Comando
```

2024-12-23 23:47 UTC, AgentePanela commented on Resources/Locale/pt-BR/Entities/Clothing/Uniforms/jumpsuits.ftl
> +    .desc = É um macacão usado pelos Oficiais do CentComm.
```suggestion
    .desc = É um macacão usado pelos Oficiais da Central de Comando
```

2024-12-23 23:47 UTC, AgentePanela commented on Resources/Locale/pt-BR/Entities/Mobs/NPCs/spacetick.ftl
> +     .desc = Cuidado com sua mordida desagradável. O CentComm relata que 90% das amputações de pernas de carga são causadas por picadas de carrapatos espaciais.
```suggestion
     .desc = Cuidado com sua mordida desagradável. A Central de Comando relata que 90% das amputações de pernas de carga são causadas por picadas de carrapatos espaciais.
```

2024-12-23 23:47 UTC, AgentePanela commented on Resources/Locale/pt-BR/Entities/Mobs/NPCs/spacetick.ftl
> +     .desc = Cuidado com sua mordida desagradável. O CentComm relata que 90% das amputações de pernas de carga são causadas por picadas de carrapatos espaciais.
```suggestion
     .desc = Cuidado com sua mordida desagradável. A Central de Comando relata que 90% das amputações de pernas de carga são causadas por picadas de carrapatos espaciais.
```

2024-12-23 23:47 UTC, AgentePanela commented on Resources/Locale/pt-BR/Entities/Mobs/Player/human.ftl
> +ent-MobHumanCentcomOfficial = Oficial do CentComm
```suggestion
ent-MobHumanCentcomOfficial = Oficial da Central de Comando
```

2024-12-23 23:47 UTC, AgentePanela commented on Resources/Locale/pt-BR/Entities/Objects/Devices/pda.ftl
> +ent-CentcomPDA = PDA de CentComm
```suggestion
ent-CentcomPDA = PDA da Central de Comando
```

2024-12-23 23:47 UTC, AgentePanela commented on Resources/Locale/pt-BR/Entities/Objects/Devices/pda.ftl
> +ent-QuartermasterPDA = PDA do intendente
```suggestion
ent-QuartermasterPDA = PDA do intendente
```
```suggestion
ent-QuartermasterPDA = PDA do intendente de logistica
```

2024-12-23 23:47 UTC, AgentePanela commented on Resources/Locale/pt-BR/Entities/Objects/Devices/pda.ftl
> +ent-CBURNPDA = PDA da DQBRN
```suggestion
ent-CBURNPDA = PDA do esquadrão de risco biologico
```

2024-12-23 23:47 UTC, AgentePanela commented on Resources/Locale/pt-BR/Entities/Objects/Fun/toys.ftl
você so usou o replace em centcomn

seria bom traduzir isso

2024-12-23 23:47 UTC, AgentePanela commented on Resources/Locale/pt-BR/Entities/Objects/Misc/bedsheets.ftl
> +ent-BedsheetCentcom = lençol do CentComm
```suggestion
ent-BedsheetCentcom = lençol da Central de Comando
```

2024-12-23 23:47 UTC, AgentePanela commented on Resources/Locale/pt-BR/Entities/Objects/Misc/identification_cards.ftl
> +ent-CentcomIDCard = ID do CentComm
```suggestion
ent-CentcomIDCard = ID da Central de Comando
```

2024-12-23 23:47 UTC, AgentePanela commented on Resources/Locale/pt-BR/Entities/Objects/Misc/identification_cards.ftl
> +ent-CentcomIDCardSyndie = ID do CentComm
```suggestion
ent-CentcomIDCardSyndie = ID da Central de Comando
```

2024-12-23 23:47 UTC, AgentePanela commented on Resources/Locale/pt-BR/Entities/Objects/Misc/identification_cards.ftl
> +ent-CBURNIDcard = ID da DQBRN
```suggestion
ent-CBURNIDcard = ID da CBURN
```

2024-12-23 23:47 UTC, AgentePanela commented on Resources/Locale/pt-BR/Entities/Objects/Misc/paper.ftl
> +ent-RubberStampCentcom = carimbo do CentComm
```suggestion
ent-RubberStampCentcom = carimbo da Central de Comando
```

2024-12-23 23:47 UTC, AgentePanela commented on Resources/Locale/pt-BR/Entities/Objects/Specific/Cargo/cargo_pallet.ftl
> +     .desc = Designa itens válidos para vender ao CentComm quando uma nave for recolhido.
```suggestion
     .desc = Designa itens válidos para vender a Central de Comando quando uma nave for recolhida
```

2024-12-23 23:47 UTC, AgentePanela commented on Resources/Locale/pt-BR/Entities/Structures/Wallmounts/Signs/posters.ftl
era bom traduzir isso tambem

2024-12-23 23:47 UTC, AgentePanela commented on Resources/Locale/pt-BR/advertisements/vending/secdrobe.ftl
> +advertisement-secdrobe-5 = O melhor tom de vermelho, totalmente não, tipo, a mesma sombra que o que os Sindicatos usam!
```suggestion
advertisement-secdrobe-5 = O melhor tom de vermelho, totalmente não, tipo, a mesma sombra que o que o Sindicato usa!
```

2024-12-23 23:47 UTC, AgentePanela commented on Resources/Locale/pt-BR/communications/communications-console-component.ftl
> +comms-console-menu-dialog-centcom-tittle = Falar com a CentComm
```suggestion
comms-console-menu-dialog-centcom-tittle = Falar com a Central de Comando
```

2024-12-23 23:47 UTC, AgentePanela commented on Resources/Locale/pt-BR/ghost/roles/ghost-role-component.ftl
> +ghost-role-information-cburn-agent-description = Um agente CentComm altamente treinado, capaz de lidar com várias ameaças.
```suggestion
ghost-role-information-cburn-agent-description = Um agente da Central de Comando altamente treinado, capaz de lidar com várias ameaças.
```

2024-12-23 23:47 UTC, AgentePanela commented on Resources/Locale/pt-BR/ghost/roles/ghost-role-component.ftl
> +ghost-role-information-centcom-official-name = oficial do CentComm
```suggestion
ghost-role-information-centcom-official-name = oficial da Central de Comando
```

2024-12-23 23:47 UTC, AgentePanela commented on Resources/Locale/pt-BR/job/job-names.ftl
> +job-name-blueshield = sentinela de comando
```suggestion
job-name-blueshield = blueshield
```
precisa um nome melhor

2024-12-23 23:47 UTC, AgentePanela commented on Resources/Locale/pt-BR/job/job-names.ftl
> +job-name-centcomoff = oficial da CentComm
```suggestion
job-name-centcomoff = oficial da Central de Comando
```

2024-12-23 23:47 UTC, AgentePanela commented on Resources/Locale/pt-BR/job/job-names.ftl
> +JobCentralCommandOfficial = oficial da CentComm
```suggestion
JobCentralCommandOfficial = oficial da Central de Comando
```

2024-12-23 23:47 UTC, AgentePanela commented on Resources/Locale/pt-BR/paper/stamp-component.ftl
> +stamp-component-stamped-name-centcom = CentComm
```suggestion
stamp-component-stamped-name-centcom = Central de Comando
```

2024-12-23 23:47 UTC, AgentePanela commented on Resources/Locale/pt-BR/prayers/prayers.ftl
> +prayer-chat-notify-centcom = CentComm
```suggestion
prayer-chat-notify-centcom = CENTCOM
```
toma cuidado com essas coisas

2024-12-23 23:47 UTC, AgentePanela commented on Resources/Locale/pt-BR/shuttles/emergency.ftl
> +emergency-shuttle-left = A nave de emergência saiu da estação. Estima-se {$transitTime} segundos até que a nave chegue à CentComm.
```suggestion
emergency-shuttle-left = A nave de emergência saiu da estação. Estima-se que a nave chegará a Central de Comando em {$transitTime} segundos.
```

2024-12-23 23:47 UTC, AgentePanela commented on Resources/Locale/pt-BR/job/job-supervisors.ftl
> +job-supervisors-centcom = aos funcionários da CentComm
```suggestion
job-supervisors-centcom = aos funcionários da Central de Comando
```

2024-12-23 23:47 UTC, AgentePanela commented on Resources/Locale/pt-BR/headset/headset-component.ftl
> +chat-radio-centcom = CentComm
```suggestion
chat-radio-centcom = CentCom
```

2024-12-23 23:47 UTC, AgentePanela commented on Resources/Locale/pt-BR/communications/communications-console-component.ftl
> +comms-console-menu-message-centcomm = Enviar mensagem para CentComm
```suggestion
comms-console-menu-message-centcomm = Enviar mensagem para CentCom
```

2024-12-24 00:37 UTC, joshepvodka commented on Resources/Locale/pt-BR/Entities/Structures/Wallmounts/Signs/posters.ftl
outro dia em outro PR

2024-12-24 00:37 UTC, joshepvodka commented on Resources/Locale/pt-BR/job/job-names.ftl
> +job-name-blueshield = sentinela de comando
a comunidade ja decidiu que prefere esse

2024-12-27 02:35 UTC, merged